-- Create missing challenges table
create table public.challenges (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone null,
  challenger_id uuid not null,
  challengee_id uuid not null,
  habit_id bigint not null,
  community_id bigint null,
  status character varying not null default 'pending',
  constraint challenges_pkey primary key (id),
  constraint challenges_challenger_id_fkey foreign key (challenger_id) references users (id) on update cascade on delete cascade,
  constraint challenges_challengee_id_fkey foreign key (challengee_id) references users (id) on update cascade on delete cascade,
  constraint challenges_habit_id_fkey foreign key (habit_id) references habits (id) on update cascade on delete cascade,
  constraint challenges_community_id_fkey foreign key (community_id) references community (id) on update cascade on delete cascade
) tablespace pg_default;

-- Create user_points table for gamification
create table public.user_points (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  points bigint not null default 0,
  constraint user_points_pkey primary key (id),
  constraint user_points_user_id_fkey foreign key (user_id) references users (id) on update cascade on delete cascade,
  constraint user_points_user_id_unique unique (user_id)
) tablespace pg_default;

-- Enable RLS for challenges table
alter table public.challenges enable row level security;

-- Allow users to see all challenges (for receiving and viewing)
create policy "Users can view challenges" on public.challenges
  for select
  using (
    auth.uid() = challenger_id or
    auth.uid() = challengee_id or
    true  -- Allow viewing for leaderboard
  );

-- Allow users to insert challenges
create policy "Users can create challenges" on public.challenges
  for insert
  with check (auth.uid() = challenger_id);

-- Allow users to update their own received challenges
create policy "Users can respond to challenges" on public.challenges
  for update
  using (auth.uid() = challengee_id or auth.uid() = challenger_id)
  with check (auth.uid() = challengee_id or auth.uid() = challenger_id);

-- Enable RLS for user_points table
alter table public.user_points enable row level security;

-- Users can view all points (for leaderboard)
create policy "Users can view all user points" on public.user_points
  for select
  using (true);

-- Users can only update their own points
create policy "Users can update own points" on public.user_points
  for update
  using (auth.uid() = user_id);
